services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs_dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: development
    depends_on:
      - redis

  redis:
    image: 'redis'
    ports:
      - '6379:6379'
    volumes:
      - './docker_volume/redis/data:/data'
