export function finnomenaKnowledge() {
  return `
    <finnomena-knowledge>
        - About Finnomena
            - เราเป็นสตาร์ทอัพด้านเทคโนโลยีการลงทุน ขับเคลื่อนโดยคนรุ่นใหม่ โดยมี คุณเจษฎา สุขทิศ และ คุณชยนนท์ รักกาญจนันท์ เป็นผู้นำขับเคลื่อนองค์กร ความฝันของพวกเราคือ จนถึงจุดหนึ่ง “เมื่อคนไทยคิดถึงการลงทุน อยากมีความรู้เรื่องลงทุน อยากได้แหล่งข้อมูลที่ดีเชื่อถือได้ เมื่อนั้นคนไทยจะคิดถึงเรา… Finnomena เริ่มก่อตั้งในปี 2558 โดยมุ่งหวังส่งมอบข้อมูลการลงทุนที่ดี ถูกต้อง และเชื่อถือได้ให้กับคนไทย ต่อมาได้ขยายกิจการและจดทะเบียนเป็น บริษัทหลักทรัพย์นายหน้าซื้อขายหน่วยลงทุน ฟินโนมีนา จำกัด โดยมี ก.ล.ต. รับรอง และในปัจจุบัน เราดูแลนักลงทุนกว่า 200,000 บัญชี ยอดเงินภายใต้การดูแลอยู่กว่า 40,000 ล้านบาท (ณ วันที่ 4 มิถุนายน 2024) ส่งผลให้ Finnomena ก้าวขึ้นเป็นอันดับ 1 ของบริษัทนายหน้าซื้อขายหน่วยลงทุนในประเทศไทย
        - Product & Services
            - Investment Knowledge Hub - News, articles, videos, podcast, market price, and more, meticulously crafted and curated to provide valuable insights and support your investment journey. Finnomena Knowledge Hub is your trusted partner in navigating the complex world of finance. https://www.facebook.com/finnomena https://www.youtube.com/@finnomena
            - Finnomena Port - Finnomena ช่วยออกแบบพอร์ตกองทุนรวมที่เหมาะสมให้กับชีวิตคุณ ติดตามภาวะตลาดให้คำแนะนำหากพอร์ตของคุณจำเป็นที่จะต้องได้รับการปรับปรุง คุณสามารถจัดการการลงทุนและติดตามผลดำเนินการพอร์ตของคุณได้ทันที ฟรี! ไม่มีค่าใช้จ่ายเพิ่มเติม ข้อมูลเพิ่่มเติม https://www.finnomena.com/port
            - Goals Navigator In partnership with Franklin Templeton - แผนการลงทุน ระดับโลก สู่ความสําเร็จของเป้าหมาย วางแผนเพื่อคุณโดยเฉพาะ หลายเป้าหมาย ติดตามผลง่าย ปรับได้ตามสถานการณ์ พร้อมแนะนำพอร์ตลงทุนที่เหมาะสม ด้วยความร่วมมือกับ Franklin Templeton ข้อมูลเพิ่มเติม https://www.finnomena.com/goals-navigator/
            - Financial Advisor Program - ก้าวสู่อาชีพแห่งอนาคต ที่ปรึกษาการลงทุนมืออาชีพฟินโนมีนา หรือ FINNOMENA Financial Advisor (FA) เริ่มต้นง่าย รายได้ดี มีระบบสนับสนุนทั้งด้านพัฒนาศักยภาพตัวเองและเทคโนโลยีการลงทุนของ FINNOMENA ข้อมูลเพิ่มเติม https://www.finnomena.com/fa/
        - FAQ
            - ซื้อกองทุนกับ Finnomena ปลอดภัย ไหม เงินหายไหม ?
                ทั้งนี้การที่ Finnomena Funds เป็นตัวแทนซื้อขายกองทุนรวม ไม่ได้หมายความว่า Finnomena Funds เป็นคนที่ดูแลหรือถือเงินของนักลงทุนไว้เอง เพราะหลังจากนักลงทุนส่งคำสั่งซื้อขายและชำระเงินเข้ามานั้น คำสั่งซื้อขายและเงินของนักลงทุนทั้งหมดจะถูกส่งให้ บลจ. ที่ดูแลกองทุนนั้น ๆ ไปบริหาร เช่นเดียวกับการซื้อกองทุนกับ บลจ. โดยตรง ดังนั้น “การซื้อกองทุนกับตัวแทน” กับ “การซื้อกองทุนกับ บลจ.” นั้นมีความปลอดภัยเทียบเท่ากัน เพราะคนที่ดูแลเงินของนักลงทุนก็คือ “ธนาคารผู้ดูแลผลประโยชน์” เหมือนกัน โดยผู้ดูแลผลประโยชน์ จะเป็นตัวแทนของผู้ถือหน่วยลงทุน ทำหน้าที่รักษาผลประโยชน์ทั้งหมดของผู้ถือหน่วยลงทุน เช่น ดูแลให้บริษัทจัดการบริหารจัดการกองทุนให้เป็นไปตามวัตถุประสงค์และนโยบายการลงทุนของกองทุนตามหนังสือชี้ชวนที่ได้รับความเห็นชอบจาก ก.ล.ต. ชำระราคาซื้อขายสินทรัพย์ของกองทุนรวม เก็บรักษาทรัพย์สินทั้งหมดของกองทุนรวม และตรวจสอบความถูกต้องของมูลค่าทรัพย์สินกองทุนรวม เป็นต้น นอกจากความเป็นกลาง และคำแนะนำในการลงทุนที่ทันกับสถานการณ์ สิ่งที่นักลงทุนจะได้รับจาก Finnomena Funds ก็คือ ความปลอดภัยของเงินลงทุนในระดับเดียวกันกับธนาคาร โดย Finnomena Funds ได้รับการรับรองถูกต้องจาก ก.ล.ต. จึงมั่นใจได้ว่าเงินของนักลงทุนจะไม่หายไปไหนแน่นอน
            - การเปิดบัญชีและเริ่มลงทุนกับ Finnomena ทำได้โดยการ
                1. ดาวน์โหลดแอพพลิเคชัน Finnomena ผ่านทาง App Store, Play Store
                2. เปิดบัญชีออนไลน์ผ่านแอพโดยไม่ต้องส่งเอกสารแต่อย่างใด
                3. สมัครตัดบัญชีอัตโนมัติเข้ากับบัญชีธนาคารของคุณ (จะมีขั้นตอนบอกในแอพพลิเคชัน)
                4. ทำรายการซื้อกองทุนที่ต้องการ
                ดูรายละเอียดเพิ่มเติมที่ https://port.finnomena.com/tax-saving-fund
            - ผู้บริหาร, Manager ของ Finnomena คือใครบ้าง ?
                - Jet (เจ๊ท) Group CEO & Co-Founder - Jet is Founder and Group CEO of FINNOMENA, providing leadership to all of the subsidiary companies. His last corporate role as CIO of CIMB-Principal Asset Management inspired his interest in Fintech and the future of wealth creation for Thailand. Jet is passionate in Innovation in Finance, holding several teaching appointments: as Director at the Faculty of Economics, Thammasat University, as Lecturer of several universities and as Founding President at Thai FinTech Association. นามปากกา FundTalk
                - Bank (แบ๊งค์) - Head Coach & Co-Founder Bank is currently Head Coach of Finnomena, focusing on skill development, strategy design and change management of the bright young team at Finnomena. As a Co-Founder, Bank was and is still responsible for Finnomena’s high-growth traction and unique content strategy. Bank’s goal is to enable over 1 million Thais to have better lives through interaction with Finnomena and its various platforms. นามปากกา Mr.Messenger
                - Gigs CEO – Finnomena Mutual Fund Brokerage & Co-Founder - Gigs is currently CEO of FINNOMENA Mutual Fund Brokerage Securities, Finnomena’s in-house trading platform. As Co-founder, Gigs, a previously seasoned Fund Manager with 20 years of experience, utilizes his expertise range from investment management to broad-based portfolio allocation, both onshore and offshore to ensure Finnomena’s products & services are both exciting and operate smoothly. He is also a Visiting Lecturer at leading universities and organizations in Thailand.
    </finnomena-knowledge>
    `;
}
